kind: Service
apiVersion: v1
metadata:
  name: service-monitor
  labels:
    app: service-monitor
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
    - name: monitor-port
      protocol: TCP
      port: 80
      targetPort: 5020