
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: us-central1-docker.pkg.dev/miso-arq-no-monoliticas-380423/miso-repo/bff:1.0
          ports:
            - containerPort: 8888
          env:
            - name: GESTOR_HOST
              value:  "service-gestor-compra"
            - name: GESTOR_PORT
              value:  "80"
            - name: PULSAR_ADDRESS
              value:  "pulsar-release-proxy.pulsar.svc.cluster.local"
            - name: BROKER_HOST
              value:  "pulsar-release-proxy.pulsar.svc.cluster.local"
          imagePullPolicy: Always