kind: Service
apiVersion: v1
metadata:
  name: service-ordenes
  annotations:
    cloud.google.com/backend-config: '{"default": "ordenes-config"}'
spec:
  type: NodePort
  selector:
    app: ordenes
  ports:
    - name: consol-port
      protocol: TCP
      port: 80
      targetPort: 5040