apiVersion: v1
kind: Service
metadata:
  name: service-db-productos
spec:
  ports:
  - port: 3306
  selector:
    app:  db-productos
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-productos
spec:
  selector:
    matchLabels:
      app: db-productos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-productos
    spec:
      containers:
      - image: mysql:8
        name:  db-productos
        env:
        - name: MYSQL_DATABASE
          value: productos
        - name: MYSQL_ROOT_PASSWORD
          value: adminadmin
        ports:
        - containerPort: 3306
          name:  db-productos
        volumeMounts:
        - name: mysql-db-productos-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-db-productos-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-db-productos-pv-claim