kind: Service
apiVersion: v1
metadata:
  name: service-gestor-compra
  annotations:
    cloud.google.com/backend-config: '{"default": "gestor-compra-config"}'
spec:
  type: NodePort
  selector:
    app: gestor-compra
  ports:
    - name: gestor-compra-port
      protocol: TCP
      port: 80
      targetPort: 5001