apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-hpa-admin-productos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-productos
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: service-monitor
      metricName: pending_messages_persistent_public_default_comandos_producto
      targetValue: 5