kind: Service
apiVersion: v1
metadata:
  name: service-admin-productos
  annotations:
    cloud.google.com/backend-config: '{"default": "admin-productos-config"}'
spec:
  type: NodePort
  selector:
    app: admin-productos
  ports:
    - name: admin-productos-port
      protocol: TCP
      port: 80
      targetPort: 5000